# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepo: sfa123/azuredemo


stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'aeb-acr'
        repository: '$(imageRepo)'
        command: buildAndPush
        dockerfile: 'AzureDemoApp/Dockerfile'
        tags: |
          $(tag)
          latest
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)/s/k8s'
        artifact: 'manifest'
        publishLocation: 'pipeline'
- stage: Deploy
  displayName: Deploy to K8s-Dev
  dependsOn: Build
  variables:
    # acrsecret: k8sexamplesacrauth
    dockerHubUrl: 'docker.io'
  jobs:
  - deployment: Deploy
    displayName: Deploy to AKS
    environment: 'k8s-dev02.test01'
    pool:
      vmImage: ubuntu-latest
    strategy:
        runOnce:
          deploy:
            steps:
            - task: KubernetesManifest@0
              inputs:
                action: 'deploy'
                kubernetesServiceConnection: 'k8s-dev02-test01-1679577742522'
                namespace: 'test01'
                manifests: |
                  $(Pipeline.Workspace)/manifests/deployment.yml
                  $(Pipeline.Workspace)/manifests/service.yml
                containers: '$(acrdevurl)/$(imageRepo):$(tag)'
