# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  imageRepo: azuredemo


stages:
- stage: Build & Push
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'aeb-acr'
        repository: '$(imageRepo)'
        command: buildAndPush
        dockerfile: 'AzureDemoApp/Dockerfile'
        tags: |
          $(tag)
          latest